AllCops:
  NewCops: enable

Style/RedundantArgument: # (new in 1.4)
  Enabled: true
Style/SwapValues: # (new in 1.1)
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
